version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data file
    tables:
      - name: product
        identifier: raw_product
        description: table identifying all products data
        columns:
          - name: products_id
            description: primary key, product identification number
            tests:
              - unique

          - name: purchse_price
            description: price we purchase the product

      - name: sales
        identifier: raw_sales
        description: table identifying all sales data
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"

        columns:
          - name: date_date
            description: date we sold the product
          - name: orders_id
            description: number of the order
          - name: pdt_id
            description: unique number of the product
          - name: revenue
            description: revenue generated per order
          - name: quantity
            description: quantity of products sold per order
      

      - name: ship
        identifier: raw_ship
        description: table identifying all shipping data
        columns:
          - name: orders_id
            description: primary key, number of the order
            tests:
              - unique
          - name: shipping_fee
            description: fee from shipping
          - name: shipping_fee_1
            description: to be removed
          - name: logcost
            description: logisitics cost
          - name: ship_cost
            description: cost generated by shipping
models:
  dbt_demo:
    marts:
      +materialized: table
